import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSideBar: [
   
    {type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Stamp-Calc',
      collapsible: true,
      collapsed: false,
      items: 
      [
        'stamp-calc/intro',
        'stamp-calc/tech-stack',
        'stamp-calc/architecture',
        'stamp-calc/endpoints',
        'stamp-calc/observability',
      ],
    },
  ],
   
};

export default sidebars;
